### ISSUE TITLE
Error when building: setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by badshah400** [scikit-hep/scikit-hep-testdata#40] opened 2020-08-20 15:06 UTC
When trying to build packages for openSUSE, using the github tagged 0.3.6 source tarball, I get the following error:

```
[   10s] + /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
[   10s] Traceback (most recent call last):
[   10s]   File "setup.py", line 7, in <module>
[   10s]     setup()
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
[   10s]     _install_setup_requires(attrs)
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 132, in _install_setup_requires
[   10s]     dist = distutils.core.Distribution(dict(
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 447, in __init__
[   10s]     _Distribution.__init__(self, {
[   10s]   File "/usr/lib64/python3.8/distutils/dist.py", line 292, in __init__
[   10s]     self.finalize_options()
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 740, in finalize_options
[   10s]     ep.load()(self)
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools_scm/integration.py", line 48, in infer_version
[   10s]     dist.metadata.version = _get_version(config)
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 148, in _get_version
[   10s]     parsed_version = _do_parse(config)
[   10s]   File "/usr/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 110, in _do_parse
[   10s]     raise LookupError(
[   10s] LookupError: setuptools-scm was unable to detect version for '/home/abuild/rpmbuild/BUILD/scikit-hep-testdata-0.3.6'.
[   10s]
[   10s] Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git
 folder) don't contain the necessary metadata and will not work.
```

However, PyPI doesn't have any of the source tarballs, only wheel files, so I am not sure how to work around this. Would be grateful for any help.

Spec file and sources here: <https://build.opensuse.org/package/show/home:badshah400:branches:science/python-scikit-hep-testdata>

**Comment by badshah400** [comment] 2020-12-13 05:43
Still an issue wth v0.3.9

**Comment by eduardo-rodrigues** [comment] 2020-12-14 12:18
Hi, can you provide details on what you're doing? I tried to run `python3 setup.py build '--executable=/usr/bin/python3 -s'` after a git clone, inside a docker container, and it all works fine, with the build simply copying files (nothing but Python code in the package).

Also, why can't you just `pip install`?

CC'ing @henryiii, far more expert on packaging, in case I'm missing something (obvious).

**Comment by badshah400** [comment] 2020-12-14 12:51
I am packaging rpms for openSUSE. Sources [here](https://build.opensuse.org/package/show/devel:languages:python:numeric/python-scikit-hep-testdata). Specifically, when building, I have to pass `export SETUPTOOLS_SCM_PRETEND_VERSION=<version>` before running `python3 setup.py build...`. Here is what happens otherwise:

```
[   11s] + /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
[   11s] Traceback (most recent call last):
[   11s]   File "setup.py", line 7, in <module>
[   11s]     setup()
[   11s]   File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 162, in setup
[   11s]     return distutils.core.setup(**attrs)
[   11s]   File "/usr/lib64/python3.8/distutils/core.py", line 108, in setup
[   11s]     _setup_distribution = dist = klass(attrs)
[   11s]   File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 447, in __init__
[   11s]     _Distribution.__init__(self, {
[   11s]   File "/usr/lib64/python3.8/distutils/dist.py", line 292, in __init__
[   11s]     self.finalize_options()
[   11s]   File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 740, in finalize_options
[   11s]     ep(self)
[   11s]   File "/usr/lib/python3.8/site-packages/setuptools_scm/integration.py", line 48, in infer_version
[   11s]     dist.metadata.version = _get_version(config)
[   11s]   File "/usr/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 148, in _get_version
[   11s]     parsed_version = _do_parse(config)
[   11s]   File "/usr/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 110, in _do_parse
[   11s]     raise LookupError(
[   11s] LookupError: setuptools-scm was unable to detect version for '/home/abuild/rpmbuild/BUILD/scikit-hep-testdata-0.3.9'.
[   11s] 
[   11s] Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
[   11s] 
[   11s] For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
[   11s] error: Bad exit status from /var/tmp/rpm-tmp.7d1wqJ (%build)
```

**Comment by eduardo-rodrigues** [comment] 2020-12-14 13:00
Oh, so this goes out of my area of knowledge :(.

Have you tried the suggestions at the bottom of the messages above? Guess yes, of course. Feel free to post at https://gitter.im/Scikit-HEP/community in case somebody can try and help ... I don't really see how to reproduce.

**Comment by badshah400** [comment] 2020-12-14 13:54
> Have you tried the suggestions at the bottom of the messages above? Guess yes, of course. Feel free to post at https://gitter.im/Scikit-HEP/community in case somebody can try and help ... I don't really see how to reproduce.

I can't try it because PyPI doesn't have any of the source tarballs (only wheels). That's part of my issue.

**Comment by eduardo-rodrigues** [comment] 2020-12-14 14:30
Fair enough. Maybe I am misunderstanding, but would the following work for you?

```
git clone -b v0.3.9 --depth 1 https://github.com/scikit-hep/scikit-hep-testdata.git
cd scikit-hep-testdata/
pip install .
```

**Comment by henryiii** [comment] 2020-12-14 14:32
We avoid providing tarballs because this is large and it cuts our required PyPI storage in half.

If you are getting a non git clone, such as the GitHub generated tarballs, then you need to provide `SETUPTOOLS_SCM_PRETEND_VERSION`, since there's no version information included in GitHub's tar files; that is correct.

Actually, for pure Python, is there a problem installing the wheels? For a built package in a packaging system, you should install from SDist, since you want your system compilers to do the build. But there's nothing to built - the wheels really just are a zip file with the required files in a specific structure, and that's all - feel free to unzip them yourself if you want.

Aside: You should never run setup.py directly - that's an implementation detail of setuptools and is not supposed to be used directly anymore. It is perfectly legal in modern setuptools to remove setup.py entirely. You should use PyPA-build or pip to do the building.

**Comment by eduardo-rodrigues** [comment] 2021-03-10 17:16
At this point I'm closing this old-ish issue. You got already a reply and I assume you're OK with it. Otherwise @badshah400 reopen if necessary.

**Closed by eduardo-rodrigues** 2021-03-10 17:16 UTC

**Comment by eduardo-rodrigues** [comment] 2021-03-10 17:27
Thanks.
