### ISSUE TITLE
second LHE testfile with easy physics

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/scikit-hep-testdata#48] opened 2021-04-12 23:55 UTC
the current LHE test file has a very complex event content which is nice for testing parsing etc but doesn't lend itself for quick tests of functionality as in https://github.com/scikit-hep/pylhe/pull/83

It would be good to have a second testfile from a simple Z->µµ process.

@matthewfeickert has one but it's 9MB which might or might not be too large

**Comment by matthewfeickert** [comment] 2021-04-13 01:53
@benkrikler @jpivarski @henryiii @eduardo-rodrigues what are your thoughts on the max size each file should be? I can of course skim this down from 1000 events to 100 or something, but it would be helpful to know in general what is the file size we should be aiming below.

**Comment by eduardo-rodrigues** [comment] 2021-04-13 11:33
Hi. So we had issues and various discussions just about a year ago on the subject of big files and limitations for PyPI. In the end (1) @jpivarski removed some non-used(-ish) files and (2) I got a PR in with PyPI and eventually we got more space per release for the `scikit-hep-testdata` package. We are safe for a bit unless we start adding large files too often, in which case we can try again to argue for more space, but let's not abuse ...

In general - meaning there can be good reasons / exceptions - test files are by definition scoped to test some feature, hence I would expect them to be rather small, often quite a lot smaller than 1 MB.  For your case above I would even imagine that a tiny file with 10-20 events would be enough? Yes it would be excellent not to care about storage (well, maybe not completely, as we all know from our HEP daily work ;-)) but constraints are what they are, and I think we should make a little effort to have test files that are exactly that, and do the job and not more. In short, it's clear that a test file with Z -> mu mu with just a handful of events should be enough for the tests you envisage, and will certainly be small enough.

BTW, I see that you are now accepting zipped files so you could even have a new file zipped? That should make such an LHE quite a bit smaller?

**Comment by lukasheinrich** [comment] 2021-04-13 11:43
Could we not have a hosted area at CERN EOS (acccessible via HTTP so it can
be moved)

we could use the scikit-hep-testdata.github.io URL and redirect as needed
to get stable URLss or maybe evenn better
submit files to zenodo and use their permanent URLs?

Best,
Lukas

**Comment by lukasheinrich** [comment] 2021-04-13 11:45
`skhep_data.data_path('foo.root', download=True)` could then download files on-damand (simillar to `torchvision` and other projects)

**Comment by jpivarski** [comment] 2021-04-13 11:51
I would love to replace this package with a stable HTTP service that we can rely on. Versioning hasn't been important at all. Reliability is the main thing, though: some Uproot tests relied on files in HepData and they had to be turned off because the service wasn't always available. There might be a longer thread from me and @kratsg about this in the issues.

**Comment by eduardo-rodrigues** [comment] 2021-04-13 12:09
Ah, yes, thanks for reminding me/us of that. In fact there have been ideas towards that from the onset, see for example what @benkrikler wrote down at the beginning of this pacakge in https://github.com/scikit-hep/scikit-hep-testdata/issues/3. There were related discussions elsewhere I'm sure, but unnecessary to dig, I reckon. Unfortunately nobody ever took the time to push some alternative forward.

I totally agree that reliability is important, and versioning not so.

**Comment by eduardo-rodrigues** [comment] 2021-04-13 12:12
See for example https://github.com/scikit-hep/scikit-hep-testdata/blob/master/src/skhep_testdata/remote_files.py. I don't think this ever really got used anywhere, though I may have lost track.

**Comment by lukasheinrich** [comment] 2021-04-13 12:19
zenodo for me is the best setup.. it allows to upload new files and each new file would trigger a new DOI (but deduplicated for unchagged files according to @tiborsimko) the urls look ilke this

```
https://zenodo.org/record/4660171/files/scikit-hep/pylhe-v0.2.1.zip
```

but we can setup a mapping in this package  `{`test.lhe`: 'https://zenodo.org/record/4660171/files/scikit-hep/pylhe-v0.2.1.zip'}` etc

**Comment by eduardo-rodrigues** [comment] 2021-04-13 12:30
So going the idea of having a YAML file such as https://github.com/scikit-hep/scikit-hep-testdata/blob/master/src/skhep_testdata/remote_datasets.yml collecting all that we need? I assume you mean that we would only be uploading the files we presently have here, and future ones, rather than each package release? Unclear from the comment on deduplication ... That's a bit of an abuse of a system such as Zenodo - not its primary raison d'etre - but would work for sure.

**Comment by eduardo-rodrigues** [comment] 2021-04-13 12:31
Maybe worth asking on the org admins mailing list if other have an opinion, since the package is for testing across the org?

**Comment by jpivarski** [comment] 2021-04-13 15:33
> zenodo for me is the best setup.

Does it mean you have a separate DOI for each file? That feels like overkill, as we have a few hundred files and it's important to organize them all with a common listing. But if Zenodo is basically hosting arbitrary files for free (reliably), then okay.

**Comment by lukasheinrich** [comment] 2021-04-13 15:43
no the entire collection has a DOI and whenever we update it (add N files) that gets a new DOI

**Comment by jpivarski** [comment] 2021-04-13 15:56
> no the entire collection has a DOI and whenever we update it (add N files) that gets a new DOI

That's good. I'm in favor of that if Zenodo's uptime is high. The first collection can be the current set of files, and then I have 21 more (average size: 9.4 MB) that should have been used in unit tests but the threshold for adding them to scikit-hep-testdata was too high.

There must be some limitations, like file size, collection size, etc. Also, what's the interface? Can we make it so that everyone in the Scikit-HEP group can add to the same collection? Is the collection a GitHub repo or something else?

**Comment by lukasheinrich** [comment] 2021-04-13 15:59
the current limitation is 50 GB but it's negotiable and we could probably have a good shot at extending that. However I don't think we will cross that anytime soon.

**Comment by henryiii** [comment] 2021-04-13 16:15
The current procedure is not ideal at all, we are duplicating the current files every time we make a new release, and we will run out of space (though, since we only "add" files, we could delete old versions, I suppose). And, of course, there's a limit. I've thought for a while this package could become an interface to a file store (like Zenodo, that's a good idea, I think). There's some initial infrastructure for that that was never (?) used, IIRC, and something like https://www.pyfilesystem.org (from the author of Rich), etc, might be useful.

The useful features in this repo could be an interface to Zenodo, a way to download the set all at once (maybe, maybe not that helpful). If it's really easy with first/third party tools already, maybe we could just use Zenodo and have clear examples in this repo of how to access files.

Could we start by making a Zenodo with this current set of data files (and matching version number, I expect)?

**Comment by lukasheinrich** [comment] 2021-04-13 16:20
for my understanding: I guess pypi does not dedupe submissions. I had the same concern for zenodo but this is what I checked w/ @tiborsimko and it seems zenodo does keep one copy of a file even if it's in multiple releases. I can create a test zenodo submission with the current files and we can see what this looks like

**Comment by henryiii** [comment] 2021-04-13 16:22
It's not a duplicate on PyPI. It's duplicated inside the zip/tar files. With Zenodo, it's separate files.

**Comment by lukasheinrich** [comment] 2021-04-13 16:29
this is what a record looks like

`https://zenodo.org/record/4683995`

with urls like

`https://zenodo.org/record/4683995/files/uproot-sample-5.30.00-lzma.root`

**Comment by henryiii** [comment] 2021-04-13 16:41
Is there an api to get the file list?

**Comment by lukasheinrich** [comment] 2021-04-13 16:42
I seem to not be able to open the file over HTTP however

```
root [1] TFile::Open("https://zenodo.org/record/4683995/files/uproot-sample-5.30.00-lzma.root?download=1")
Error in <TDavixFile::DavixReadBuffer>: can not read data with davix: Failure HTTP 429 : Unexpected server error: 429 , while  readding after 3 attempts (256)
Error in <TDavixFile::Init>: https://zenodo.org/record/4683995/files/uproot-sample-5.30.00-lzma.root failed to read the file type data.
```

```
>>> uproot.open('https://zenodo.org/record/4683995/files/uproot-sample-5.30.00-lzma.root')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/reading.py", line 145, in open
    **options  # NOTE: a comma after **options breaks Python 2
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/reading.py", line 586, in __init__
    self._begin_chunk, _file_header_fields_small, {}
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/cursor.py", line 193, in fields
    return format.unpack(chunk.get(start, stop, self, context))
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/chunk.py", line 361, in get
    self.wait()
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/chunk.py", line 314, in wait
    self._raw_data = numpy.frombuffer(self._future.result(), dtype=self._dtype)
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/futures.py", line 126, in result
    delayed_raise(*self._excinfo)
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/futures.py", line 288, in _run
    self._result = self._task(resource)
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/http.py", line 247, in task
    return resource.get(connection, start, stop)
  File "/Users/lukasheinrich/Code/pylhe/_env/lib/python3.7/site-packages/uproot/source/http.py", line 218, in get
    response.status, self._file_path
OSError: remote server responded with status 429, rather than 206 (range requests)
for URL https://zenodo.org/record/4683995/files/uproot-sample-5.30.00-lzma.root
>>> 
```

**Comment by lukasheinrich** [comment] 2021-04-13 16:42
yes zenodo has a REST API

https://developers.zenodo.org/

**Comment by henryiii** [comment] 2021-04-13 16:43
429, too many requests error?

**Comment by jpivarski** [comment] 2021-04-13 16:44
They rate limit the requests. That's the gotcha.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

It makes sense when the files are citations, rarely opened, but for unit tests, we'll be accessing these same files _a lot_.

**Comment by lukasheinrich** [comment] 2021-04-13 16:46
```
curl -sSL https://zenodo.org/api/records/4683995|jq '.files[].links.self'
```

**Comment by henryiii** [comment] 2021-04-13 16:48
How severely? We could download all the files in one go at the beginning of the unit test. We could also cache the files in GHA. Can you get a zip of the whole submission?

**Comment by henryiii** [comment] 2021-04-13 16:49
(I also think part of the problem is reading a file may cause more access vs. simply downloading it, but we can download it, as long as multiple runs and multiple projects do not collide.

**Comment by lukasheinrich** [comment] 2021-04-13 16:53
doesn't look like one can get the full archive as a zip, but downloading a
single file via curl and then opening in uproot works for me. this
download/local cache is sth the python code could do for us.. but we should
check whether the rate limit is intended

**Comment by jpivarski** [comment] 2021-04-13 17:02
Due to the structure of a ROOT file, a directory listing is two requests (one to find the header, the next to find the list of keys) and every other type of object except the TTree ecosystem is one request. For a TTree, it's one request for the metadata and then one request for each TBasket, unless the server supports multi-part GET (which is not very widespread; one question on StackOverflow even asked why anyone would want such a thing).

Considering that these are all, by definition, small files, the download-and-read-locally pattern is better.

-------------------

The fact that it is so heavily rate limited—you already ran into the issue in this small test—makes me wary of Zenodo as a solution. Sure, we can cache on GitHub Actions, but then we'd be relying on the cache for functionality (to be able to run our tests), not for performance. This seems very brittle to me. Surely there are more reliable ways to store/retrieve small files, right?

We _don't_ need git's versioning and we don't need Zenodo's DOIs. We won't be referencing these test files in a paper or anything. We _do_ need high availability (regardless of whether we cache it further downstream). An AWS bucket would do it, except then we'd have to manage permissions, or maybe something at CERN.

**Comment by lukasheinrich** [comment] 2021-04-13 17:13
alternatively CERN offers hosting from EOS via links a la


https://recastwww.web.cern.ch/recastwww/data/scikit-hep-testdata/scikit-hep-testdata/src/skhep_testdata/data/uproot-double32-float16.root

this would be a manully managed EOS directory

we could also (ab-)use github's own static hosting via github.io and just commit the files to the repo

**Comment by henryiii** [comment] 2021-04-13 17:21
You can also attach files to a GitHub release, and download from there. New files could come from new releases only.


Using the following script, I was able to download 1/2 of the files in 10 seconds, the final 1/2 of the files returned 429's.

```python
import requests
import concurrent.futures
import pathlib

response = requests.get("https://zenodo.org/api/records/4683995")
response.raise_for_status()

files = [f["links"]["self"] for f in response.json()["files"]]

d = pathlib.Path("tmpfiles")
d.mkdir()


def download_file(url: str) -> int:
    filename = url.split("/")[-1]
    print(f"Getting {filename}")
    response = requests.get(url)
    try:
        response.raise_for_status()
    except Exception:
        pass
    else:
        with open(d / filename, "wb") as f:
            f.write(response.content)
    print(f"{filename} : {response.status_code}")
    return response.status_code


with concurrent.futures.ThreadPoolExecutor(max_workers=32) as executor:
    results = executor.map(download_file, files)

for f, r in zip(files, results):
    print(f, r, sep=": ")
```

**Comment by jpivarski** [comment] 2021-04-13 17:24
With a GitHub repo, we know how we would grant access. [GitHub's file size limits](https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota) are well within our needs (individual files must be less than 100 MB; the repo must be less than 5 GB). If the git history gets bogged down, it could be rebased into one commit because we're not interested in history. Maybe GitHub's large file service would make more sense, though.

**Comment by henryiii** [comment] 2021-04-13 17:25
GooFit's test files are attached to the `v1.0.0` release, see here: https://github.com/GooFit/GooFit/releases/tag/v1.0.0 - the testing suite downloads them from here. They don't bog down the repo, and they are easily available.

I think the large file service would run into rate limits?

**Comment by henryiii** [comment] 2021-04-13 17:26
https://docs.github.com/en/github/managing-large-files/about-storage-and-bandwidth-usage#bandwidth-quota

**Comment by jpivarski** [comment] 2021-04-13 17:29
I like the idea of attaching files to a release if that can be done incrementally. Ideally, I'd want to be able to add a file about once or twice a week. (I've been not writing as many Uproot tests as I should because minting a new test file is hard.)

Those LFS limits are severe.

**Comment by lukasheinrich** [comment] 2021-04-13 18:02
maybe the easiest is then to just ruthlessly commit to git (no LFS) and use github.io as static hosting?

**Comment by henryiii** [comment] 2021-04-13 18:36
We currently have them in git, so it's actually no different than now, just with the files no longer part of the PyPI release, but downloaded manually. We could even generate the list of files and place it in the SDist.

**Comment by henryiii** [comment] 2021-04-13 18:36
We could also just always install from git - it's not really a public facing package that must be installed from PyPI.

**Comment by jpivarski** [comment] 2021-04-13 18:37
I suppose a `tests_require` can point to a git repo?

**Comment by henryiii** [comment] 2021-04-13 18:38
`tests_require` is deprecated and should not be present in our repos. Extras such as `tests` can point at git.

**Comment by lukasheinrich** [comment] 2021-04-13 18:43
I think the experience of having

```
pip install skhep_testdata
>>> import skhep_testdata
... skhep_testdata.path('bla.root') # which triggers a download if not
shipped via sdist
```

is nice and I would keep that.. but whether to ship the data itself or
always download e.g. from a github.io URL is sth we can discuss

**Comment by henryiii** [comment] 2021-04-13 18:47
We could store the files in GitHub (like we do now), then ship SDists and Wheels with just the list, not the files. When they try to load the file, if it doesn't exist, they grab it from GitHub, using their version number as the tag in the URL (or just bake the current commit in, that's easy to do, too). If you get it from git, then you get all the files "for free", so if you need a version for an airplane ride, you can install from git. (We'd have to have an environment variable for making the SDist without the files, but again, easy to do).

**Comment by lukasheinrich** [comment] 2021-04-13 18:49
that makes sense to me.. if the git storage becomes an issue at some point we can move to some other distr. mechanism

another option for airplane mode is

```
import skhep_testdata
skhep_testdata.download_all()
```

**Comment by henryiii** [comment] 2021-04-13 18:51
Yes, that's probably better than complicating the setup, on reflection.

**Comment by jpivarski** [comment] 2021-04-13 19:11
I'll often want to add files, and this will mean a whole release cycle (as it does now), but I suppose I can do that with less guilt.

**Comment by henryiii** [comment] 2021-04-13 19:14
If all that's being released is a handful of python files and a list, that's pretty low-guilt, yes. :) Also, we could make sure you can run from git for development, releasing would only be needed when packages were released, not for each item in a PR (for example).

**Comment by matthewfeickert** [comment] 2021-04-13 23:13
> We could store the files in GitHub (like we do now), then ship SDists and Wheels with just the list, not the files. When they try to load the file, if it doesn't exist, they grab it from GitHub, using their version number as the tag in the URL (or just bake the current commit in, that's easy to do, too). If you get it from git, then you get all the files "for free", so if you need a version for an airplane ride, you can install from git. (We'd have to have an environment variable for making the SDist without the files, but again, easy to do).

This sounds really good IMO.

**Comment by kratsg** [comment] 2021-04-14 14:42
fyi gh-pages as an orphaned branch should do just fine.

**Comment by henryiii** [comment] 2021-04-14 17:57
Please take a look at #51, where this is implemented.

**Comment by jpivarski** [comment] 2021-04-16 19:29
By the way, everyone on this thread: I'm testing and deploying @henryiii's changes now. It will be scikit-hep-testdata 0.4.0 (and possibly 0.4.1, depending on how things go).

Also, the default branch is being renamed to "main," since the code now depends on the branch name and now seems like the least difficult time to do it.

**Comment by jpivarski** [comment] 2021-04-16 20:01
The [last release](https://pypi.org/project/scikit-hep-testdata/0.3.12/#files) in PyPI was 79 MB; [this one](https://pypi.org/project/scikit-hep-testdata/0.4.0/#files) is 10 kB. With an adjustment (my own fault), Uproot can still be tested (scikit-hep/uproot4#337). I'm going to try adding some files that were blocking a few Uproot tests.

**Comment by jpivarski** [comment] 2021-04-16 20:13
Going though the PR procedure to upload a file seems unnecessary. I'm thinking it could be a matter of policy that simply adding a file to the database should be a commit-to-main (possibly through the web interface) action. If there are any disagreements, let me know.

**Comment by henryiii** [comment] 2021-04-16 21:07
Depends on who it is. Core devs (like you) can commit to main. It would be nice to track what gets added for other users though. I don't want this to grow without bound - each file should have good reason to be added and not a duplicate of another file, shouldn't be larger than is absolutely has to be, etc.

**Comment by henryiii** [comment] 2021-04-16 21:10
I forgot, but conda-forge will need to be handled specially (probably with pulling a checkout and using the special env var). There shouldn't be as much of an issue making those files large (as long as this doesn't get too huge or release daily).

**Comment by lukasheinrich** [comment] 2021-04-16 21:20
awesome.. nice to see this resolved so quickly - this will probably carry us for quite some time! @matthewfeickert want tu dump your Z->µµ file?

**Closed** 2021-04-19 07:54 UTC
